### ISSUE TITLE
Replace BeautifulSoup with regex

### ISSUE THREAD

**Issue by M0r13n** [Esshahn/pyscraper#1]
Hey,

for me BeautifulSoup always feels quite oversized for such small projects. Did you consider using a simple regular expression instead? 

I assembled a quick demo:

```python
regex = re.compile('id="priceblock_ourprice".*[0-9.,]')
regex.findall(page.text)[0].split('>')[-1] # >>> 25,27
```

This could remove bs4 as a dependency and is also a bit faster (0,22s vs 0,60s for 100 finds on my machine). 

I would like to hear your feedback about this idea. :-)

**Comment by Esshahn** [comment]
Hey M0r13n! Thank you for your suggestion. It sounds pretty great and having less dependencies is always preferred. I'm just starting with Python and haven't used bs4 before, so it didn't come my mind to replace it with regex.

Would you care to do a PR?

**Comment by M0r13n** [comment]
Hey,

thank you for your reply. I just implemented the scraper using only regular expressions. I noticed that it's especially hard to extract the title from the raw HTML. There are quite a few edge cases that make the code harder to read and also reduce it's robustness. This seems to be the opposite of what I originally wanted to achieve. Therefore it might be better to just keep using BS4.

**Comment by Esshahn** [comment]
No worries, I think it was very well worth a shot.
Thanks for your support :)
